name: Notify Hugging Face on Push

on:
  push:
    branches:
      - main

jobs:
  notify-model:
    runs-on: ubuntu-latest
    steps:
      - name: Send Notification to Hugging Face Model
        run: |
          curl -X POST https://huggingface.co/spaces/AIEONE/sgentic-mind-model/api/predict \
            -H "Content-Type: application/json" \
            -d '{"inputs": "GitHub repo has been updated!"}'
